name: Deploy to AWS S3 & CloudFront

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust the version if needed

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build

      - name: Deploy to S3
        uses: aws-actions/s3-sync@v1
        with:
          bucket: my-vite-bucket
          region: us-east-1           # Replace with your AWS region
          local-dir: dist             # Upload the built app
          delete: true

      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          distribution-id: EC5VJLPCY6T83
          paths: "/*"
